### ISSUE TITLE
auto .... bidding ? 

### ISSUE THREAD

**Issue by KhairulAzmi21** [oRastor/fut22-web-app#6]
is it possible we enhance this scripts by adding auto bidding ?

it would be great if we can do that . 

By the way, I appreciate your efforts . Its really good.

**Comment by oRastor** [comment]
> is it possible we enhance this scripts by adding auto bidding ?

Can you explain what do you mean?

**Comment by KhairulAzmi21** [comment]
I mean .. adding feature auto bid ? 

instead of auto buy .

**Comment by oRastor** [comment]
Ok, I understand. 
It's possible, but there are a lot of changes that need to do to implement this feature. I'm still waiting for transfer market opening for my account =(.  
For now, I have not time to play FIFA (for transfer market opening) and implementing this feature. Maybe later, sorry.

**Comment by KhairulAzmi21** [comment]
If my 2nd account already got access to transfer market, I will give you access for that .

EA really made joke of this, they never tell how many games we need to play in order to enable transfer market....

**Comment by AndyHeinz** [comment]
Hi, is this still in development?
Do you habe ideas how IT could work? I'd like to see what you have planned, and See if its workin. I could Do some adjustments of needed.

**Comment by oRastor** [comment]
No, I have not time for developing new functionalities. Users can make money now without this feature.
