### ISSUE TITLE
Auto Buy Gone?

### ISSUE THREAD

**Issue by Lenna187** [oRastor/fut22-web-app#83]
So i was buying and selling players and suddenly the auto buy function was gone?
I did try to reinstall tampermonkey and the script but still no result.

**Comment by oRastor** [comment]
https://github.com/oRastor/fut22-web-app/blob/master/fut22-autobuyer.user.js updated script 20 minutes ago

**Comment by Lenna187** [comment]
> https://github.com/oRastor/fut22-web-app/blob/master/fut22-autobuyer.user.js updated script 20 minutes ago

I installed it but nothing happened though

**Comment by manolo75** [comment]
With that new one, we can't save filter anymore.

**Comment by Lenna187** [comment]
> https://github.com/oRastor/fut22-web-app/blob/master/fut22-autobuyer.user.js updated script 20 minutes ago

It's back ty though, what did you changed?

**Comment by oRastor** [comment]
its a fix after last web app release

**Comment by Lenna187** [comment]
Aah okay thanks bro

**Comment by teim98** [comment]
Hi, it doesn't work also the update version. It read the script in tampermonkey saying that the autobuyer is enabled but opening the fut webapp there is nothing.
(I've removed the last js and then downloaded and installed the updated one).
Anyone can help me?

**Comment by oRastor** [comment]
man

> Hi, it doesn't work also the update version. It read the script in tampermonkey saying that the autobuyer is enabled but opening the fut webapp there is nothing. (I've removed the last js and then downloaded and installed the updated one). Anyone can help me?

tampermonkey did not update your version automatically
