### ISSUE TITLE
Non scripts in execution on TamperMonkey

### ISSUE THREAD

**Issue by Batita77** [oRastor/fut22-web-app#87]
Need some help please. I just installed TamperMonkey on Google Chrome on a Windows laptop and added the autobuyer userscript. But when i run the web app the autobuyer doesn´t appear and when i click on the Tampermonkey icon it says that "there are no scripts in executions". 

Maybe i am missing some step, can someone please help?

Allready have the autobuyer working on a iMac, amazing work by oRastor, many thanks.

**Comment by oRastor** [comment]
Works only on English language of FUT 22 web app (https://www.ea.com/fifa/ultimate-team/web-app/)!

**Comment by Batita77** [comment]
Solved, many thanks
